### ISSUE TITLE
Tests for lexical scoping semantics in eval contexts

### ISSUE THREAD

**Issue by jugglinmike** [bocoup/test262#115]
Primarily [18.2.1.2Runtime Semantics: EvalDeclarationInstantiation](https://tc39.github.io/ecma262/#sec-evaldeclarationinstantiation)

**Comment by littledan** [comment]
Eval can go in all sorts of places, such as

```
(({[eval("var x")]: y}) => x)([1])
```

(which I think should be a ReferenceError, but I may be mistaken)

Putting eval all over the place gets at lots of weird edge cases of
scoping. V8 has put a lot of work into getting these right, but we're
still not positive we do everywhere, and we haven't gotten very
complete test coverage from our fuzzer. We've had lots of crashing
bugs and also lots of scope mis-resolution. One piece of difficulty is
arrow function parameters, whose scopes aren't immediately clear when
being parsed from left to right.

This may be more easy to get a full set of tests running using the new
tools for programmatic test generation (even if it's not automated with
the dev branch yet).
