### ISSUE TITLE
Should we filter on frontmatter "Description"

### ISSUE THREAD

**Issue by spectranaut** [bocoup/test262#137]
In prepack's filtering, they filter on keywords in the description. Could these keywords be moved to something like the feature? Should we implement this in the yaml file for filtering we'd like to define?

```
https://github.com/facebook/prepack/blob/master/scripts/test262-runner.js#L1146
function filterDescription(data: BannerData): boolean {
  // For now, "Complex tests" is used in the description of some
  // encode/decodeURI tests to indicate that they are long running.
  // Filter these
  return (
    !data.description.includes("Complex tests") &&
    !data.description.includes("iterating") &&
    !data.description.includes("iterable")
  );
}
```

**Comment by leobalter** [comment]
I like to have this documented here, but I'm strongly in favor to not add any filter based in the test description.

For Prepack, we can identify the files being filtered out and sort out a proper alternative.

Each test description is subjective and its value might change anytime without any specific policy or review process. e.g.: someone described almost all decodeURI tests as "Complex tests", but the current filter prevents someone else to use the same words in tests for other unrelated feature or replace the decodeURI tests without using the same words again.
