### ISSUE TITLE
String methods - Instance

### ISSUE THREAD

**Issue by jugglinmike** [bocoup/test262#25]
Methods:
- [x] `String.prototype.codePointAt`,
- [x] `String.prototype.normalize`
- [x] `String.prototype.repeat`
- [x] `String.prototype.startsWith`
- [x] `String.prototype.endsWith`
- [x] `String.prototype.includes`

**Comment by leobalter** [comment]
every list method has at least a PR. I'll close the issue when we get all merged.

**Comment by leobalter** [comment]
all merged!
