### ISSUE TITLE
Array methods - Static

### ISSUE THREAD

**Issue by jugglinmike** [bocoup/test262#26]
Methods:
- [x] [`Array.from`](http://www.ecma-international.org/ecma-262/6.0/#sec-array.from)
- [x] [`Array.of`](http://www.ecma-international.org/ecma-262/6.0/#sec-array.of)

**Comment by jugglinmike** [comment]
Heads up: my work for `@@iterator` (as required by gh-31) involves testing a large chunk of `Array.from`. I will update gh-31 when I have completed writing those tests; please coordinate with me if you'd like to work on `Array.from` before that time.

**Comment by leobalter** [comment]
We got Array.from merged, but I'll take a look on the coverage.
