### ISSUE TITLE
Array methods - Instance

### ISSUE THREAD

**Issue by jugglinmike** [bocoup/test262#27]
Methods:
- [x] [`Array.prototype.copyWithin`](http://www.ecma-international.org/ecma-262/6.0/#sec-array.prototype.copywithin)
- [x] [`Array.prototype.entries`](http://www.ecma-international.org/ecma-262/6.0/#sec-array.prototype.entries)
- [x] [`Array.prototype.fill`](http://www.ecma-international.org/ecma-262/6.0/#sec-array.prototype.fill)
- [x] [`Array.prototype.find`](http://www.ecma-international.org/ecma-262/6.0/#sec-array.prototype.find)
- [x] [`Array.prototype.findIndex`](http://www.ecma-international.org/ecma-262/6.0/#sec-array.prototype.findindex)
- [x] [`Array.prototype.keys`](http://www.ecma-international.org/ecma-262/6.0/#sec-array.prototype.keys)
- [x] [`Array.prototype.values`](http://www.ecma-international.org/ecma-262/6.0/#sec-array.prototype.values)
- [x] [`Array.prototype[Symbol.iterator]`](http://www.ecma-international.org/ecma-262/6.0/#sec-array.prototype-@@iterator)

**Comment by leobalter** [comment]
starting with: keys, values and entries

**Comment by leobalter** [comment]
We already have some tests for find and findIndex but some are inappropriate. I'll fix them up.

**Comment by leobalter** [comment]
We've got only copyWithin remaining to close this one

**Comment by leobalter** [comment]
done! :)
