### ISSUE TITLE
Math - Methods & Constants

### ISSUE THREAD

**Issue by jugglinmike** [bocoup/test262#28]

**Comment by leobalter** [comment]
Methods to test:
- [x] `Math.acosh( x )`
- [x] `Math.asinh( x )`
- [x] `Math.atanh( x )`
- [x] `Math.cbrt( x )`
- [x] `Math.cosh( x )`
- [x] `Math.expm1( x )`
- [x] `Math.imul( x, y )`
- [x] `Math.log1p( x )`
- [x] `Math.log10( x )`
- [ ] `Math.log2( x )`
- [x] `Math.sign( x )`
- [x] `Math.sinh( x )`
- [x] `Math.tanh( x )`

**Comment by leobalter** [comment]
Already made at b6e870d

Just found a case sensitive issue on log2, PR already opened.
