### ISSUE TITLE
Extension hooks

### ISSUE THREAD

**Issue by jugglinmike** [bocoup/test262#31]
- [x] `Symbol.hasInstance`
- [x] `Symbol.isConcatSpreadable`
- [x] `Symbol.iterator`
- [x] `Symbol.match`
- [x] `Symbol.replace`
- [x] `Symbol.search`
- [x] `Symbol.species`
- [x] `Symbol.split`
- [x] `Symbol.toPrimitive`
- [x] `Symbol.toStringTag`
- [x] `Symbol.unscopables`

source: [6.1.5.1 Well-Known Symbols](http://www.ecma-international.org/ecma-262/6.0/#sec-regexpinitialize)

**Comment by jugglinmike** [comment]
I'm working on `Symbol.hasInstance` now!

**Comment by jugglinmike** [comment]
I'm now working on `Symbol.isConcatSpreadable`

**Comment by jugglinmike** [comment]
On to `Symbol.iterator`

**Comment by jugglinmike** [comment]
I've started writing tests for `Symbol.match`. This is a big one!

**Comment by jugglinmike** [comment]
`Symbol.isConcatSpreadable` tests merged via https://github.com/tc39/test262/pull/371

**Comment by jugglinmike** [comment]
`@@iterator` tests merged via https://github.com/tc39/test262/pull/377

**Comment by jugglinmike** [comment]
Now working on tests for `@@replace`

**Comment by jugglinmike** [comment]
The next biggest Symbol is `@@split`, so I'm starting that now!

**Comment by jugglinmike** [comment]
On to `@@search`!

**Comment by jugglinmike** [comment]
- `@@replace` tests merged via https://github.com/tc39/test262/pull/402
- `@@split` tests merged via https://github.com/tc39/test262/pull/407
- `@@search` tests merged via https://github.com/tc39/test262/pull/412
- `@@toStringTag` tests merged via https://github.com/tc39/test262/pull/414

**Comment by jugglinmike** [comment]
`@@hasInstance` tests merged via https://github.com/tc39/test262/pull/370

**Comment by jugglinmike** [comment]
`@@match` tests merged via https://github.com/tc39/test262/pull/399

**Comment by jugglinmike** [comment]
`@@toPrimitive` tests merged via https://github.com/tc39/test262/pull/418

**Comment by rwaldron** [comment]
@jugglinmike this is incredible work!

**Comment by jugglinmike** [comment]
Thanks, Rick!

**Comment by jugglinmike** [comment]
`@@unscopables` tests merged via https://github.com/tc39/test262/pull/434. That rounds off this issue--now closing.

**Comment by leobalter** [comment]
:clap: :clap: 

Congrats!
