### ISSUE TITLE
Implement test for subclassing built-ins

### ISSUE THREAD

**Issue by jugglinmike** [bocoup/test262#35]

**Comment by leobalter** [comment]
Browsing the specs I'll try to list so points of interest. Currently listed on https://gist.github.com/leobalter/86e84476a9d36403a56f which content I'll bring to this issue when I finish it.

**Comment by leobalter** [comment]
Done! The list below gives an initial idea of each built-in objects we might write tests for. Those are designed to be subclassed. It's good to check their descriptions as some has particularities.
- [x] 19.1.1 The Object Constructor
- [x] 19.2.1 The Function Constructor
- [x] 19.3.1 The Boolean Constructor
- [x] 19.4.1 The Symbol Constructor
- [x] 19.5.1 The Error Constructor
- [x] 19.5.6.1 NativeError Constructors
- [x] 20.1.1 The Number Constructor
- [x] 20.3.2 The Date Constructor
- [x] 21.1.1 The String Constructor
- [x] 21.2.3 The RegExp Constructor
- [x] 22.1.1 The Array Constructor
- [x] 22.2.4 The TypedArray Constructors
- [x] 23.1.1 The Map Constructor
- [x] 23.2.1 The Set Constructor
- [x] 23.3.1 The WeakMap Constructor
- [x] 23.4.1 The WeakSet Constructor
- [x] 24.1.2 The ArrayBuffer Constructor
- [x] 24.2.2 The DataView Constructor
- [x] 25.2.1 The GeneratorFunction Constructor
- [x] 25.4.3 The Promise Constructor
- Should we include subclassing for instances of builtin objects? 

If we want to add, the following are not specifically designed to be subclassed, observing the item [14.5.14 6.f](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-runtime-semantics-classdefinitionevaluation): 
- 26.2.1 The Proxy Constructor (Proxy is a constructor and it might be 
- 26.1 The Reflect Object
- 26.3 Module Namespace Objects
- 20.2 Math
- 24.3 JSON

Chapter [18.3](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-constructor-properties-of-the-global-object) has a good summary to follow.
