### ISSUE TITLE
Spread operator

### ISSUE THREAD

**Issue by jugglinmike** [bocoup/test262#36]

**Comment by jugglinmike** [comment]
Since this pattern applies in both [array initializers](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-array-initializer) and [arguments lists](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-argument-lists), it's another feature that is susceptible to long-term coverage fragmentation. I'm adding the "blocked on duplication solution" to reflect this.

**Comment by brianloveswords** [comment]
Captured in #50
