### ISSUE TITLE
Identify list of inherited built-in calls

### ISSUE THREAD

**Issue by brianloveswords** [bocoup/test262#41]

**Comment by leobalter** [comment]
As mentioned on #35, I finished this list already:
- 19.1.1 The Object Constructor
- 19.2.1 The Function Constructor
- 19.3.1 The Boolean Constructor
- 19.4.1 The Symbol Constructor
- 19.5.1 The Error Constructor
- 19.5.6.1 NativeError Constructors
- 20.1.1 The Number Constructor
- 20.3.2 The Date Constructor
- 21.1.1 The String Constructor
- 21.2.3 The RegExp Constructor
- 22.1.1 The Array Constructor
- 22.2.4 The TypedArray Constructors
- 23.1.1 The Map Constructor
- 23.2.1 The Set Constructor
- 23.3.1 The WeakMap Constructor
- 23.4.1 The WeakSet Constructor
- 24.1.2 The ArrayBuffer Constructor
- 24.2.2 The DataView Constructor
- 25.2.1 The GeneratorFunction Constructor
- 25.4.3 The Promise Constructor

Other built-in objects not specifically designed to be subclassed (observes item [14.5.14 6.f](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-runtime-semantics-classdefinitionevaluation): 
- 26.2.1 The Proxy Constructor
- 26.1 The Reflect Object
- 26.3 Module Namespace Objects
- 20.2 Math
- 24.3 JSON

**Comment by leobalter** [comment]
As an extra note: some objects are not specifically designed to be subclassed, but that does not mean they cannot be. e.g. Proxy
