### ISSUE TITLE
Tests for TypedArray constructors

### ISSUE THREAD

**Issue by brianloveswords** [bocoup/test262#58]

**Comment by leobalter** [comment]
- [ ] **22.2.1.1 %TypedArray% ( )** - all steps
- [ ] **22.2.1.2 %TypedArray% ( length )** - all steps
- [ ] **22.2.1.3 %TypedArray% ( typedArray )** - all steps
- [ ] **22.2.1.4 %TypedArray% ( object )** - all steps
- [ ] **22.2.4.1 TypedArray( ... argumentsList)** steps 3 and 4 - return abrupt from getPrototypeOf on the constructor. This is hard to achieve, but it sounds possible using Proxies
- [ ] **22.2.4.1 TypedArray( ... argumentsList)** step 5 - "If IsConstructor (super) is false, throw a TypeError exception." - I still need to figure out how to reach that part
