### ISSUE TITLE
Destructuring - BindingPattern

### ISSUE THREAD

**Issue by jugglinmike** [bocoup/test262#7]

**Comment by jugglinmike** [comment]
This was partially addressed by the now-merged https://github.com/tc39/test262/pull/267 . Test262 still lacks coverage for the pattern's behavior in "ForIn/Of" heads, but I'm reluctant to copy-and-paste because I don't think parity will be enforced in the long term. This is generally a problem for many language features, so we're actively discussing a solution in https://github.com/tc39/test262/issues/276

**Comment by leobalter** [comment]
Beyond the already reported parts, we may also find some tests partially covering Destructuring Binding on the assignment, rest parameters and default parameters tests.

tests for ES7 rest parameters with binding pattern are [already](https://github.com/tc39/test262/blob/master/test/language/rest-parameters/object-pattern.js) [present](https://github.com/tc39/test262/blob/master/test/language/rest-parameters/array-pattern.js).

It would be great if we move tc39#276 forward, @jugglinmike insights are amazing.

One of my concern is if we do not have Mike's approach, we should create possible duplicated tests on a binding/destructuring folder to assert each part of [Chapter 13.3.3](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-destructuring-binding-patterns).

**Comment by brianloveswords** [comment]
Captured in #43
