### ISSUE TITLE
Destructuring - Assignment

### ISSUE THREAD

**Issue by jugglinmike** [bocoup/test262#8]

**Comment by jugglinmike** [comment]
This was partially addressed by https://github.com/tc39/test262/pull/267. Test262 is still missing coverage for the pattern's appearance in ForIn/Of heads, so this issue should remain open until equivalent tests are added. Doing that in a maintainable way will require as-yet-undefined infrastructure currently being discussed in https://github.com/tc39/test262/issues/276. This is not the only issue that requires that infrastructure, so I have created a new label titled "blocked on duplication solution" to communicate this status.

**Comment by brianloveswords** [comment]
Captured in #44
